controllers:
  resource: ../src/Shared/Infrastructure/Controller/
  type: annotation

kernel:
  resource: ../src/Shared/Infrastructure/Kernel.php
  type: annotation

api:
  defaults:
    _format: json
  resource: './routes/api/'
  type: directory
  prefix: /api

#app.swagger_ui:
#  path: /api/doc
#  methods: GET
#  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }